server:
  port: 8081

logging:
  level:
    org.hibernate.sql : debug

spring:
  profiles:
    active: dev
  application:
    name: the-parabole-event

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

